Add command rewrite design doc
wpilibsuite/design-docs pull request #7
Opened 2019-09-13 13:51 UTC by Oblarg

The API details in the doc are somewhat outdated, but for purposes of justifying the rewrite it is still entirely accurate.

2019-09-13 15:54 UTC, Daltz333 commented
@AustinShalit

2019-10-01 13:31 UTC, AustinShalit submitted a review, later dismissed

2019-10-01 13:42 UTC, AustinShalit requested changes

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +The problems with the current command framework fall generally into three major categories:
Off by one error?
```suggestion
The areas for improvement with the current command framework fall generally into four major categories:
```

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +1.  Poor readability/maintainability.
```suggestion
1.  Maintainability
```

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +2.  Poor encapsulation/separation of responsibilities.
```suggestion
2.  Encapsulation & separation of responsibilities
```

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +3.  Unnecessarily restrictive API design.
```suggestion
3.  Restrictive API design
```

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +4.  Clutter.
```suggestion
4.  API Clutter
```

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +These three problems are interrelated, but I will summarize each in turn.
```suggestion
These four areas are interrelated, but I will summarize each in turn.
```

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +The rewritten Command-based framework seeks to rectify the above problems.  A broad overview of the changes introduced in the rewrite is as follows:
```suggestion
The rewritten Command-based framework seeks to improve on the areas listed above.  A broad overview of the changes introduced in the rewrite is as follows:
```

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +## Why rewrite the framework? (Problem Summary)
Can you please rewrite this section to be less condemning of the old framework? Teams have successfully used it for 10+ years and I think writing about it in this way is not good for it or WPILib. See some of my inline comments.

2019-10-01 13:42 UTC, AustinShalit commented on CommandRewriteDesignDoc.md
> +
Extra EOL.
```suggestion
```

2019-10-06 22:19 UTC, AustinShalit approved these changes

2019-10-06 22:34 UTC, merged